import {
  BabyIcon,
  BedIcon,
  BookAIcon,
  Car,
  Home,
  LaptopIcon,
  ShirtIcon,
  VolleyballIcon,
} from "lucide-react";

export const categories = [
  {
    id: 1,
    name: "Electronics & Gadgets",
    value: "Electronics",
    icon: LaptopIcon,
    link: "/app/browse?category=Electronics",
    count: 234,
  },
  {
    id: 2,
    name: "Vehicles",
    value: "Vehicles",
    icon: Car,
    link: "/app/browse?category=Vehicles",
    count: 89,
  },
  {
    id: 3,
    name: "Furniture",
    value: "Furniture",
    icon: BedIcon,
    link: "/app/browse?category=Furniture",
    count: 156,
  },
  {
    id: 4,
    name: "Clothing & Fashion",
    value: "Clothes",
    icon: ShirtIcon,
    link: "/app/browse?category=Clothes",
    count: 312,
  },
  {
    id: 5,
    name: "Books & Education",
    value: "Books",
    icon: BookAIcon,
    link: "/app/browse?category=Books",
    count: 78,
  },
  {
    id: 6,
    name: "Sports & Outdoors",
    value: "Sports",
    icon: VolleyballIcon,
    link: "/app/browse?category=Sports",
    count: 67,
  },
  {
    id: 7,
    name: "Home & Garden",
    value: "Home",
    icon: Home,
    link: "/app/browse?category=Home",
    count: 145,
  },
  {
    id: 8,
    name: "Baby & Kids",
    value: "Baby",
    icon: BabyIcon,
    link: "/app/browse?category=Baby",
    count: 89,
  },
];