import {
  LayoutDashboard,
  Package,
  FolderTree,
  Tags,
  ShoppingCart,
  Users,
  Store,
  CreditCard,
  Receipt,
  TicketPercent,
  Star,
  MessageSquare,
  Bell,
  Boxes,
  Truck,
  Undo2,
  BarChart3,
  FileBarChart,
  TrendingUp,
  Megaphone,
  Image,
  Newspaper,
  CircleHelp,
  Settings,
  ShieldCheck,
  User,
  History,
  DatabaseBackup,
  LifeBuoy,
  LogOut,
} from "lucide-react";

export const menuItems = [
  { icon: <LayoutDashboard />, text: "Dashboard" },
  { icon: <Package />, text: "Products" },
  { icon: <FolderTree />, text: "Categories" },
  { icon: <Tags />, text: "Brand" },
  { icon: <ShoppingCart />, text: "Orders" },
  { icon: <Users />, text: "Customers" },
  { icon: <Store />, text: "Seller" },
  { icon: <CreditCard />, text: "Payments" },
  { icon: <Receipt />, text: "Transactions" },
  { icon: <TicketPercent />, text: "Cupon" },
  { icon: <Star />, text: "Reviews" },
  { icon: <MessageSquare />, text: "Messages" },
  { icon: <Bell />, text: "Notifications" },
  { icon: <Boxes />, text: "Inventory" },
  { icon: <Truck />, text: "Shipping" },
  { icon: <Undo2 />, text: "Returns" },
  { icon: <BarChart3 />, text: "Analaytics" },
  { icon: <FileBarChart />, text: "Reports" },
  { icon: <TrendingUp />, text: "Sales" },
  { icon: <Megaphone />, text: "Marketing" },
  { icon: <Image />, text: "Banners" },
  { icon: <Newspaper />, text: "Blogs" },
  { icon: <CircleHelp />, text: "FAQ" },
  { icon: <Settings />, text: "Settings" },
  { icon: <ShieldCheck />, text: "Roles & Permissions" },
  { icon: <User />, text: "Profile" },
  { icon: <History />, text: "Activity Logs" },
  { icon: <DatabaseBackup />, text: "Backup" },
  { icon: <LifeBuoy />, text: "Support" },
  { icon: <LogOut />, text: "LOgout" },
];
