export const chatData = [
  {
    id: 1,
    seller: "Minyamr Kelemu",
    avatar: "https://i.pravatar.cc/150?img=1",
    product: "iPhone 13 Pro",
    productImage: "products/iphone-13-pro.jpg",
    lastMessage: "Yes, it is still available.",
    location: "Addis Ababa, Ethiopia",
    lastSent: "2 min ago",
    price: "$999",
    time: "2 min",
    unread: 2,
    online: true,
  },
  {
    id: 2,
    seller: "Rahel Gedefew",
    avatar: "https://i.pravatar.cc/150?img=2",
    product: "Dell XPS 15",
    productImage: "products/dell-xps-15.jpg",
    lastMessage: "Can you reduce the price?",
    location: "Bahirdar, Ethiopia",
    lastSent: "1 day ago",
    price: "$1,299",
    time: "Yesterday",
    unread: 0,
    online: false,
  },
];
